In [1]:
# 경고 메세지가 안나오게..
import warnings
warnings.filterwarnings('ignore')

# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# KFold
from sklearn.model_selection import KFold           # 랜덤하게 섞어서 자를 수도 있고, 순서대로 자를 수도 있음
from sklearn.model_selection import StratifiedKFold # 결과 데이터의 비율이 최대한 균등하게 들어갈 수 있도록!

# 교차검증 함수
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate

# 학습 데이터와 검증 데이터로 나누는 함수
from sklearn.model_selection import train_test_split

# 데이터 전처리
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 하이퍼 파라미터 튜닝
from sklearn.model_selection import GridSearchCV

# 평가함수
from sklearn.metrics import accuracy_score

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift

# 차원축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 딥러닝
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf

# 저장
import pickle

# 그래프 설정
plt.rcParams['font.family']='Malgun Gothic'
# 맥용 plt.rcParams['font.family']='AppleGothic'
plt.rcParams['font.size'] = 16
plt.rcParams['figure.figsize'] = 20, 10
plt.rcParams['axes.unicode_minus'] = False

In [2]:
# 준비된 수술 환자 데이터를 가져온다
# 1이 생존, 0이 사망

df1 = pd.read_csv('../data/ThoraricSurgery.csv')
df1.head()

293  1   3.8   2.8  0  0.1  0.2  0.3  0.4  0.5  12  0.6  0.7  0.8  1.1  \
0    1  2  2.88  2.16  1    0    0    0    1    1  14    0    0    0    1   
1    8  2  3.19  2.50  1    0    0    0    1    0  11    0    0    1    1   
2   14  2  3.98  3.06  2    0    0    0    1    1  14    0    0    0    1   
3   17  2  2.21  1.88  0    0    1    0    0    0  12    0    0    0    1   
4   18  2  2.96  1.67  0    0    0    0    0    0  12    0    0    0    1   

   0.9  62  0.10  
0    0  60     0  
1    0  66     1  
2    0  80     1  
3    0  56     0  
4    0  61     0

In [3]:
# 입력과 결과 데이터로 나눈다

x = df1.drop('0.10', axis=1)
y = df1['0.10']

display(x)
display(y)

293  1   3.8   2.8  0  0.1  0.2  0.3  0.4  0.5  12  0.6  0.7  0.8  1.1  \
0      1  2  2.88  2.16  1    0    0    0    1    1  14    0    0    0    1   
1      8  2  3.19  2.50  1    0    0    0    1    0  11    0    0    1    1   
2     14  2  3.98  3.06  2    0    0    0    1    1  14    0    0    0    1   
3     17  2  2.21  1.88  0    0    1    0    0    0  12    0    0    0    1   
4     18  2  2.96  1.67  0    0    0    0    0    0  12    0    0    0    1   
..   ... ..   ...   ... ..  ...  ...  ...  ...  ...  ..  ...  ...  ...  ...   
464   98  6  3.04  2.40  2    0    0    0    1    0  11    0    0    0    1   
465  369  6  3.88  2.72  1    0    0    0    1    0  12    0    0    0    1   
466  406  6  5.36  3.96  1    0    0    0    1    0  12    0    0    0    0   
467   25  8  4.32  3.20  0    0    0    0    0    0  11    0    0    0    0   
468  447  8  5.20  4.10  0    0    0    0    0    0  12    0    0    0    0   

     0.9  62  
0      0  60  
1      0  66  
2      0  80  
3      0  56  
4      0  61  
..   ...  ..  
464    0  76  
465    0  77  
466    0  62  
467    0  58  
468    0  49  

[469 rows x 17 columns]

0      0
1      1
2      1
3      0
4      0
      ..
464    0
465    0
466    0
467    1
468    0
Name: 0.10, Length: 469, dtype: int64

In [4]:
# 학습데이터와 검증용으로 나눈다

train_X, test_X, train_y, test_y = train_test_split(x, y)

In [5]:
# 머신러닝
# 딥러닝이 선형모델을 쓰기 때문에 똑같이 Logi

model1 = LogisticRegression()
model1.fit(train_X, train_y)

LogisticRegression()

In [6]:
# 평가

pred1 = model1.predict(test_X)
pred1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [7]:
r1 = accuracy_score(test_y, pred1)
r1

0.847457627118644

In [8]:
# 딥러닝 구조를 결정한다

model2 = Sequential()
model2.add(Dense(30, input_dim=17, activation='relu'))
model2.add(Dense(1, activation='sigmoid'))

In [9]:
# 딥러닝 실행

model2.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
model2.fit(train_X, train_y, epochs=30, batch_size=10)

Epoch 1/30
36/36 [==============================] - 1s 2ms/step - loss: 0.3496 - accuracy: 0.6255
Epoch 2/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1268 - accuracy: 0.8730
Epoch 3/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1767 - accuracy: 0.8226
Epoch 4/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1482 - accuracy: 0.8510
Epoch 5/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1426 - accuracy: 0.8569
Epoch 6/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1583 - accuracy: 0.8398
Epoch 7/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1784 - accuracy: 0.8171
Epoch 8/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1394 - accuracy: 0.8587
Epoch 9/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1558 - accuracy: 0.8421
Epoch 10/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1282 - accuracy: 0.8710
Epoch 11/30
36/36 [

In [10]:
# 예측 결과 추출(예측결과가 값이 1일 확률)
pred2 = model2.predict(test_X)
pred2

array([[1.62245455e-15],
       [2.05813616e-04],
       [5.53401448e-02],
       [8.39326829e-02],
       [7.61513199e-20],
       [4.23618443e-02],
       [9.12046663e-24],
       [3.02208466e-20],
       [7.31838902e-16],
       [8.37036623e-06],
       [4.67047516e-13],
       [1.85780040e-21],
       [3.33522920e-09],
       [6.51378637e-29],
       [2.91718815e-25],
       [8.46037656e-05],
       [1.18301327e-21],
       [2.31756276e-05],
       [3.09469696e-19],
       [3.03363723e-11],
       [7.01380414e-14],
       [2.49088183e-02],
       [7.81377405e-03],
       [1.70848440e-22],
       [4.75859381e-02],
       [5.25695214e-07],
       [9.70363250e-20],
       [1.84504717e-19],
       [4.76080195e-17],
       [8.72791422e-12],
       [3.85635681e-02],
       [1.25039816e-02],
       [5.59028097e-18],
       [1.30366311e-06],
       [8.45044106e-02],
       [1.17038867e-25],
       [6.24689048e-13],
       [1.43793194e-13],
       [1.35899139e-24],
       [1.55055746e-10],


In [13]:
# 예측 결과를 생성한다

result2 = (pred2 >= 0.5).astype(int)
result2

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [14]:
r2 = accuracy_score(test_y, result2)
r2

0.847457627118644

- 머신러닝과 딥러닝의 정확도가 똑같이 나옴

# 단순한 데이터는 머신러닝이 낫다
# 수치 형태로 되어 있으면 머신러닝으로만 해도 가능