### MSE(Mean Square Error, cost) : 잔차(실제값과 예측값의 차이) 제곱의 평균 -> SSE를 표준화한 개념

In [1]:
import numpy as np

In [4]:
# 기울기 a와 y절편 b

기울기 = 3
y절편 = 76

In [5]:
# 입력과 결과

입력 = [2, 4, 6, 8]
결과 = [81, 93, 91, 97]

In [6]:
# 입력된 값에 따라 결과를 예측하는 함수

def predict(x):
    return 기울기 * x + y절편

In [7]:
# 예측결과를 추출한다
# 예측 결과를 담을 리스트

pred_list = []

for v1 in 입력:
    a1 = predict(v1)
    pred_list.append(a1)
    
pred_list

[82, 88, 94, 100]

In [8]:
# 계산을 쉽게 하기 위해 ndarray를 생성한다
# 리스트끼리는 빼기 연산이 안됨!!

array1 = np.array(pred_list)
array2 = np.array(결과)

print(array1)
print(array2)

[ 82  88  94 100]
[81 93 91 97]


In [9]:
# 진짜 결과와 예측 결과를 뺀 값을 가져온다

array3 = array1 - array2
print(array3)

[ 1 -5  3  3]


In [10]:
# 제곱을 구한다

array4 = array3 ** 2
print(array4)

[ 1 25  9  9]


In [11]:
# 평균을 구한다

mse = array4.mean()
print(f'평균 제곱 오차 값 : {mse}')

평균 제곱 오차 값 : 11.0
