In [1]:
# 경고 메시지가 안나오게..
import warnings
warnings.filterwarnings('ignore')

# 기본
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('seaborn-whitegrid')
import missingno

# KFold
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 교차 검증 함수
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate

# 학습 데이터와 검증데이터로 나누는 함수
from sklearn.model_selection import train_test_split

# 데이터 전처리
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 하이퍼 파라미터 튜닝
from sklearn.model_selection import GridSearchCV

# 평가함수
from sklearn.metrics import accuracy_score

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift

# 차원축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 딥러닝
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf

from keras.utils import np_utils
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Embedding

# 다중분류를 위한 핫-윈 인코더
from keras.utils import to_categorical

# 저장된 딥러닝 모델을 복구하는 함수
from keras.models import load_model

# epoch마다 모델을 저장하는 함수
from keras.callbacks import ModelCheckpoint

# 더이상 성능 향상이 이루어지지 않는다면 조기 중단시킬 수 있는 함수
from keras.callbacks import EarlyStopping

# 문장을 잘라준다
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import text_to_word_sequence

# 저장
import pickle

# 시간 모듈
import time

# 그래프 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['font.size'] = 16
plt.rcParams['figure.figsize'] = 20, 10
plt.rcParams['axes.unicode_minus'] = False

In [2]:
# 데이터를 읽어온다
df1 = pd.read_csv('../../data/naver_star_data.csv')
df1

평점                                                평가글  \
0       1.0  B급 이하전편보다 퇴보된 CG, 중구난방식 연출, 러닝타임 늘리기 위한 쓸모없는 컷...   
1       3.0  이딴 영화가 평점 8점 후반대라는 게 믿기지 않는다. 역시 네이버 평점은 믿고 걸러...   
2       6.0  역시 원더우먼 영화는 주연배우 갤가돗과 크리스파인이 다 살리네.. 감독은 확실히 영...   
3       2.0          진짜 개노잼이다.. 1편이랑 같은 감독맞나?러닝타임도 길어서 개지루함 ㄹㅇ   
4       1.0  히어로물의 액션을 기대했음. 그러나 졸렬한 액션과 이상한 전개로 마지막 영화관을 나...   
...     ...                                                ...   
260670  1.0                     이렇게 높은평점 받을 영화는 아닌듯..딱7~8점초반영화   
260671  1.0  섹시마일드. 왜 이영화가 평점이 높은데. 그냥 그런영화면 재미없다고 하세요. 괜히 ...   
260672  1.0        영화 시작후 1분만에 욕이 나왔다.발연기 발연출 초저질영화의 대가다.XX!!!   
260673  1.0  먼가 오늘날의 뻔한 한국드라마로 보였다. 그리고 난 그것이 싫다.... 명작들은 세...   
260674  1.0  전혀 재미없음. 헛소리만 지껄임. 아무 의미도 내용도 없음. 정신나간 20대여자들이...   

                    작성자              작성날짜    공감수   비공감수  
0       코꾸뇨우옹(pott****)  2020.12.24 09:08  873.0  289.0  
1              juum****  2020.12.23 22:19  620.0  232.0  
2          없음(jymi****)  2020.12.23 17:05  480.0  168.0  
3       민중의빠따(gkst****)  2020.12.23 22:51  433.0  143.0  
4        시리우스(sojh****)  2020.12.23 13:34  412.0  198.0  
...                 ...               ...    ...    ...  
260670  dbsgk(jsjh****)  2015.02.18 15:25    5.0   12.0  
260671         heli****  2015.10.08 16:51    1.0    9.0  
260672         appl****  2012.03.26 13:37    3.0   11.0  
260673    느와르(igel****)  2017.01.01 00:31    0.0   10.0  
260674    코스챠(chao****)  2017.01.27 01:30    4.0   31.0  

[260675 rows x 6 columns]

In [3]:
# 평점과 평가글만 가져온다
df2 = df1[['평점', '평가글']]
df2.head()

평점                                                평가글
0  1.0  B급 이하전편보다 퇴보된 CG, 중구난방식 연출, 러닝타임 늘리기 위한 쓸모없는 컷...
1  3.0  이딴 영화가 평점 8점 후반대라는 게 믿기지 않는다. 역시 네이버 평점은 믿고 걸러...
2  6.0  역시 원더우먼 영화는 주연배우 갤가돗과 크리스파인이 다 살리네.. 감독은 확실히 영...
3  2.0          진짜 개노잼이다.. 1편이랑 같은 감독맞나?러닝타임도 길어서 개지루함 ㄹㅇ
4  1.0  히어로물의 액션을 기대했음. 그러나 졸렬한 액션과 이상한 전개로 마지막 영화관을 나...

In [4]:
# 결측치는 문자열이 아닌 실수타입으로 인식해서
# 아예 결측치를 제거하자

df2.dropna(inplace=True)
df2.isna().sum()

평점     0
평가글    0
dtype: int64

In [5]:
# 평점이 5점 이하는 0으로 바꿔준다
a1 = df2.query('평점 <= 5').index
df2.loc[a1, '평점'] = 0

In [6]:
# 평점이 6점 이상은 1로 바꿔준다.
a1 = df2.query('평점 > 5').index
df2.loc[a1, '평점'] = 1

In [7]:
df2['평점'].value_counts()

1.0    217358
0.0     36333
Name: 평점, dtype: int64

In [8]:
# 평가글 추출
docs = df2['평가글'].values
docs

array(['B급 이하전편보다 퇴보된 CG, 중구난방식 연출, 러닝타임 늘리기 위한 쓸모없는 컷, 부족한 액션, 영화가 주는 시사점도 없고 보는 내내 오그라들고 나가고싶었음.',
       '이딴 영화가 평점 8점 후반대라는 게 믿기지 않는다. 역시 네이버 평점은 믿고 걸러야 한다.개연성 중요하게 생각하는 사람들은 보면서 토할 수도 있으니까 조심.중후반부터 느금마사급 전개가 계속 이어지기 때문에 정신잡기...',
       '역시 원더우먼 영화는 주연배우 갤가돗과 크리스파인이 다 살리네.. 감독은 확실히 영화 못 찍음.... 예전 샤를리즈 테론 영화 몬스터만해도 배우가 다 살림... 원더우먼 1도 악당 허술하고 매력없고 스토리도 전개가 ...',
       ..., '영화 시작후 1분만에 욕이 나왔다.발연기 발연출 초저질영화의 대가다.XX!!!',
       '먼가 오늘날의 뻔한 한국드라마로 보였다. 그리고 난 그것이 싫다.... 명작들은 세대가 넘어가도 언제나 명작소리를 듣지만 이건 머랄까 다 보고나면 저런 스토리 요즘에 차고넘쳐서 지루할 정도로 많은데....이런 느낌이...',
       '전혀 재미없음. 헛소리만 지껄임. 아무 의미도 내용도 없음. 정신나간 20대여자들이나 좋아할듯'],
      dtype=object)

In [9]:
# 결과 추출
classes = df2['평점'].values
classes

array([0., 0., 1., ..., 0., 0., 0.])

In [10]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
token.word_index

{'영화': 1,
 '너무': 2,
 '정말': 3,
 '진짜': 4,
 '잘': 5,
 '더': 6,
 '이': 7,
 '수': 8,
 '보고': 9,
 '그냥': 10,
 '다': 11,
 '영화를': 12,
 '본': 13,
 '그': 14,
 '좀': 15,
 '봤는데': 16,
 '좋은': 17,
 '꼭': 18,
 '최고의': 19,
 '많이': 20,
 '스토리': 21,
 '연기': 22,
 '영화가': 23,
 '재밌게': 24,
 '또': 25,
 '영화는': 26,
 '있는': 27,
 '것': 28,
 '여운이': 29,
 '다시': 30,
 '그리고': 31,
 '왜': 32,
 '마지막': 33,
 '보는': 34,
 'ㅠㅠ': 35,
 '내': 36,
 '이런': 37,
 '감동': 38,
 '한': 39,
 '봤습니다': 40,
 '최고': 41,
 '오랜만에': 42,
 '아름다운': 43,
 '영화입니다': 44,
 '하는': 45,
 '좋고': 46,
 '이렇게': 47,
 '내가': 48,
 '역시': 49,
 '없는': 50,
 '볼': 51,
 '봤어요': 52,
 '눈물': 53,
 '하지만': 54,
 '보세요': 55,
 '내내': 56,
 '조금': 57,
 '재미있게': 58,
 '계속': 59,
 '좋았어요': 60,
 '눈물이': 61,
 '보면': 62,
 '마지막에': 63,
 '한번': 64,
 '재밌어요': 65,
 '평점': 66,
 '참': 67,
 '스토리가': 68,
 '와': 69,
 '배우들': 70,
 '연기도': 71,
 '아': 72,
 '넘': 73,
 '모두': 74,
 '솔직히': 75,
 '음악': 76,
 '그래도': 77,
 'ㅎㅎ': 78,
 '난': 79,
 '같은': 80,
 '좋았다': 81,
 'ㅋㅋ': 82,
 'ㅠ': 83,
 '가장': 84,
 '느낌': 85,
 '안': 86,
 '연기가': 87,
 '다른': 88,
 '봐도': 89,
 '스토리도': 90,

In [11]:
len(token.word_index)

383512

In [12]:
# 단어사전을 통해 문장의 각 단어를 숫자로 변환한다
x = token.texts_to_sequences(docs)
len(x)

253691

In [13]:
# 한 문장의 최대 단어수를 가져온다
max_count = 0

for x2 in x:
    # 현재 문장의 글자수
    count1 = len(x2)
    # 현재 문장의 글자수가 이전 최대 수치보다 많으면 덮어씌운다
    if max_count < count1:
        max_count = count1
        
max_count

48

In [14]:
# 패딩 : 서로 길이가 다른 리스트의 개수를 맞춰준다
padded_x = pad_sequences(x, max_count)
padded_x

array([[     0,      0,      0, ...,     56,   9293,  17911],
       [     0,      0,      0, ...,  63776,    231, 101809],
       [     0,      0,      0, ...,  25328,     90,    422],
       ...,
       [     0,      0,      0, ..., 383505, 383506,  27644],
       [     0,      0,      0, ...,   1432,     37,    239],
       [     0,      0,      0, ...,  12420, 383512,   7694]])

In [15]:
# 단어의 개수를 구한다
word_size = len(token.word_index) + 1
word_size

383513

In [16]:
model = Sequential()
model.add(Embedding(word_size, 8, input_length=48))

model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [17]:
model.compile(loss='binary_crossentropy', metrics=['accuracy'], optimizer='adam')

In [18]:
model.fit(padded_x, classes, epochs=20)

Epoch 1/20
7928/7928 [==============================] - 225s 28ms/step - loss: 0.3117 - accuracy: 0.8763
Epoch 2/20
7928/7928 [==============================] - 226s 29ms/step - loss: 0.1546 - accuracy: 0.9400
Epoch 3/20
7928/7928 [==============================] - 226s 29ms/step - loss: 0.0938 - accuracy: 0.9666
Epoch 4/20
7928/7928 [==============================] - 226s 28ms/step - loss: 0.0591 - accuracy: 0.9807
Epoch 5/20
7928/7928 [==============================] - 202s 26ms/step - loss: 0.0403 - accuracy: 0.9873
Epoch 6/20
7928/7928 [==============================] - 196s 25ms/step - loss: 0.0289 - accuracy: 0.9908
Epoch 7/20
7928/7928 [==============================] - 198s 25ms/step - loss: 0.0212 - accuracy: 0.9933
Epoch 8/20
7928/7928 [==============================] - 199s 25ms/step - loss: 0.0164 - accuracy: 0.9949
Epoch 9/20
7928/7928 [==============================] - 199s 25ms/step - loss: 0.0130 - accuracy: 0.9959
Epoch 10/20
7928/7928 [==============================] 

In [19]:
# 학습 데이터에 대한 성능평가

model.evaluate(padded_x, classes)[1]

7928/7928 [==============================] - 11s 1ms/step - loss: 0.0037 - accuracy: 0.9987


0.9987465143203735

In [20]:
docs = [
    '이 영화 재미있어요',
    '이 영화 재미없어요',
    '추천 드립니다',
    '추천 드리지 않습니다'
]

In [21]:
x = token.texts_to_sequences(docs)
padded_x = pad_sequences(x, 48)
pred = (model.predict(padded_x)>0.5).astype('int32')

In [22]:
pred

array([[1],
       [0],
       [1],
       [0]])