### 이미지 크기 동일하게 색상도 RGB로 동일하게!

- 색상이 있는 이미지를 검색한다.
- 본 파일에서는 딥러닝을 하기 전에 이미지 전처리 작업을 한다.
- 이미지의 크기가 모두 달라서 머신러닝으로 다루기가 어렵다.
- 일정한 크기로 새 이미지를 만들고 24비트 RGB 컬러 형태로 변환하여 모든 이미지의 크기와 색감을 통일시킨다.
- 그리고 머신러닝을 쉽게 하기 위해 ndarray형태로 변환한 다음, 이것을 파일로 저장한다.

In [1]:
from PIL import Image
import os
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
# 하위에 있는 폴더들의 목록을 가져온다.
categories = list(os.walk('img/101_ObjectCategories'))[0][1]
categories

['accordion',
 'airplanes',
 'anchor',
 'ant',
 'BACKGROUND_Google',
 'barrel',
 'bass',
 'beaver',
 'binocular',
 'bonsai',
 'brain',
 'brontosaurus',
 'buddha',
 'butterfly',
 'camera',
 'cannon',
 'car_side',
 'ceiling_fan',
 'cellphone',
 'chair',
 'chandelier',
 'cougar_body',
 'cougar_face',
 'crab',
 'crayfish',
 'crocodile',
 'crocodile_head',
 'cup',
 'dalmatian',
 'dollar_bill',
 'dolphin',
 'dragonfly',
 'electric_guitar',
 'elephant',
 'emu',
 'euphonium',
 'ewer',
 'Faces',
 'Faces_easy',
 'ferry',
 'flamingo',
 'flamingo_head',
 'garfield',
 'gerenuk',
 'gramophone',
 'grand_piano',
 'hawksbill',
 'headphone',
 'hedgehog',
 'helicopter',
 'ibis',
 'inline_skate',
 'joshua_tree',
 'kangaroo',
 'ketch',
 'lamp',
 'laptop',
 'Leopards',
 'llama',
 'lobster',
 'lotus',
 'mandolin',
 'mayfly',
 'menorah',
 'metronome',
 'minaret',
 'Motorbikes',
 'nautilus',
 'octopus',
 'okapi',
 'pagoda',
 'panda',
 'pigeon',
 'pizza',
 'platypus',
 'pyramid',
 'revolver',
 'rhino',
 'rooste

In [7]:
# 이미지 파일들을 가지고 있는 경로의 루트
caltech_dir = 'img/101_ObjectCategories'
# 전체 카테고리의 개수
nb_class = len(categories)

In [8]:
# 이미지의 크기
image_w = 64
image_h = 64
pixels = image_w * image_h * 3 # RGB

In [10]:
import glob

# 이미지 변형
X = []
Y = []
# 반복문
for idx, cat in enumerate(categories) :
    # print(idx, cat)
    # 이미지의 개수에 만큼의 0을 채운 리스트를 생성한다..
    label = [0 for i in range(nb_class)]
    # print(label)
    # 현재 번째의 값을 1로 채워준다.
    label[idx] = 1
    # 읽어올 이미지 경로
    image_dir = caltech_dir + '/' + cat
    # 이미지 파일
    # 해당 경로에 있는 모든 이미지 파일들의 목록을 가져온다.
    files = glob.glob(image_dir + '/*.jpg')
    # print(files)
    # 파일의 수만큼 반복한다.
    for i, f in enumerate(files) :
        # 이미지를 읽어온다.
        img = Image.open(f)
        # 24bit RGB로 변환
        img = img.convert('RGB')
        # 이미지 크기 조정
        img = img.resize((image_w, image_h))
        # 행렬로 변환
        data = np.asarray(img)
        # 리스트에 담는다.
        X.append(data)
        Y.append(label)
        # 10회마다 한번씩 출력한다.
        if i % 10 == 0 :
            print(i, '\n', data)

X = np.array(X)
Y = np.array(Y)

0 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
10 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
20 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  

100 
 [[[255 255 255]
  [255 255 255]
  [254 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
110 
 [[[255 255 255]
  [255 255 255]
  [254 255 255]
  ...
  [210 218 205]
  [210 218 205]
  [210 218 205]]

 [[255 255 255]
  [255 255 255]
  [254 255 255]
  ...
  [209 217 203]
  [211 219 204]
  [210 218 204]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [210 218 203]
  [210 218 203]
  [210 218 203]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 2

260 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 254]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 254]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 254]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 254 254]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 254]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [254 255 255]
  [255 255 255]
  [255 255 255]]]
270 
 [[[ 48 114 162]
  [ 50 116 164]
  [ 50 115 162]
  ...
  [108 139 168]
  [113 140 163]
  [119 143 162]]

 [[ 49 115 163]
  [ 50 116 164]
  [ 52 117 164]
  ...
  [105 137 167]
  [112 140 164]
  [119 144 164]]

 [[ 52 118 166]
  [ 50 116 164]
  [ 52 117 164]
  ...
  [103 137 168]
  [112 140 165]
  [120 146 166]]

 ...

 [[ 54 120 168]
  [ 55 121 169]
  [ 55 1

430 
 [[[106 123 133]
  [107 124 134]
  [109 125 137]
  ...
  [255 255 255]
  [254 255 253]
  [255 255 255]]

 [[106 123 133]
  [108 125 135]
  [109 125 137]
  ...
  [255 255 255]
  [254 255 253]
  [255 255 255]]

 [[106 123 133]
  [108 125 135]
  [108 125 136]
  ...
  [255 255 255]
  [254 255 253]
  [255 255 255]]

 ...

 [[149 135 107]
  [152 136 110]
  [157 141 115]
  ...
  [255 255 255]
  [254 255 254]
  [255 255 255]]

 [[149 134 105]
  [153 138 109]
  [158 143 113]
  ...
  [255 255 255]
  [254 255 254]
  [255 255 255]]

 [[150 135 106]
  [155 140 111]
  [159 144 115]
  ...
  [255 255 255]
  [254 255 254]
  [255 255 255]]]
440 
 [[[255 255 255]
  [165 176 183]
  [124 142 157]
  ...
  [134 150 163]
  [134 150 163]
  [133 147 159]]

 [[255 255 255]
  [165 175 183]
  [124 142 157]
  ...
  [134 150 163]
  [134 150 163]
  [133 147 159]]

 [[255 255 255]
  [166 176 184]
  [125 143 158]
  ...
  [135 151 164]
  [134 150 163]
  [133 147 159]]

 ...

 [[254 255 255]
  [218 201 182]
  [207 1

610 
 [[[255 255 255]
  [191 197 197]
  [135 151 151]
  ...
  [254 254 254]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [182 190 191]
  [118 137 140]
  ...
  [254 254 253]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [175 186 190]
  [108 132 140]
  ...
  [253 253 253]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [195 185 158]
  [153 127  85]
  ...
  [254 253 251]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [198 187 163]
  [153 127  89]
  ...
  [254 254 251]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [203 193 169]
  [169 143 107]
  ...
  [254 254 251]
  [255 255 255]
  [255 255 255]]]
620 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [254 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [254 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [254 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 2

790 
 [[[  7 101 153]
  [  8 101 154]
  [  6 103 154]
  ...
  [  1 105 156]
  [  1 105 156]
  [  0 104 155]]

 [[  7 101 153]
  [  8 101 154]
  [  6 103 154]
  ...
  [  1 105 156]
  [  1 105 156]
  [  0 104 155]]

 [[  7 101 153]
  [  8 101 154]
  [  7 103 154]
  ...
  [  1 105 156]
  [  1 105 156]
  [  1 105 156]]

 ...

 [[  1 110 159]
  [  2 108 158]
  [  3 107 158]
  ...
  [138 152 163]
  [142 156 167]
  [145 159 170]]

 [[  1 110 159]
  [  2 108 158]
  [  3 107 158]
  ...
  [137 151 162]
  [141 155 166]
  [144 158 169]]

 [[  1 110 159]
  [  3 109 159]
  [  3 108 159]
  ...
  [137 151 162]
  [141 155 166]
  [142 156 167]]]
0 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0

100 
 [[[201 201 201]
  [230 230 230]
  [230 230 230]
  ...
  [230 230 230]
  [230 230 230]
  [177 177 177]]

 [[219 219 219]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [186 186 186]]

 [[217 217 217]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [185 185 184]]

 ...

 [[218 218 218]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [185 185 184]]

 [[221 221 221]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [188 188 187]]

 [[175 175 175]
  [192 192 192]
  [191 191 191]
  ...
  [192 191 191]
  [192 191 191]
  [147 147 147]]]
110 
 [[[157 198 220]
  [162 195 216]
  [170 193 211]
  ...
  [167 197 219]
  [168 191 209]
  [181 192 202]]

 [[141 172 223]
  [140 170 218]
  [143 171 213]
  ...
  [143 177 230]
  [145 174 216]
  [158 175 200]]

 [[142 174 223]
  [143 175 219]
  [144 176 214]
  ...
  [141 181 230]
  [145 180 217]
  [155 178 198]]

 ...

 [[110 107 144]
  [108 107 145]
  [120 1

240 
 [[[ 67   7  11]
  [  0   1   2]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 72   6   7]
  [  0   1   2]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 70   5   8]
  [  0   0   2]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[ 70   5   8]
  [  0   0   2]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 68   5   8]
  [  0   0   2]
  [  0   0   0]
  ...
  [ 26  30  29]
  [ 38  41  41]
  [ 27  30  30]]

 [[103   8  11]
  [ 45   5   7]
  [ 44   5   7]
  ...
  [ 78  37  40]
  [100  60  62]
  [ 82  42  45]]]
250 
 [[[175 175 175]
  [213 213 213]
  [211 211 211]
  ...
  [211 211 211]
  [212 212 212]
  [174 174 174]]

 [[213 213 213]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [214 214 214]]

 [[212 212 212]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [213 213 213]]

 ...

 [[213 213 213]
  [255 255 255]
  [213 2

450 
 [[[255 255   0]
  [255 255   0]
  [255 255   0]
  ...
  [255 255   0]
  [255 255   0]
  [255 255   0]]

 [[255 255   0]
  [255 255   0]
  [255 255   0]
  ...
  [255 255   0]
  [255 255   0]
  [255 255   0]]

 [[255 255   0]
  [255 255   0]
  [255 255   0]
  ...
  [255 255   0]
  [255 255   0]
  [255 255   0]]

 ...

 [[255 255   0]
  [255 255   0]
  [247 247  27]
  ...
  [241 240   3]
  [255 255   0]
  [255 255   0]]

 [[255 255   0]
  [255 255   0]
  [249 249  13]
  ...
  [243 242   4]
  [255 255   0]
  [255 255   0]]

 [[255 255   0]
  [255 255   0]
  [255 255   0]
  ...
  [255 255   0]
  [255 255   0]
  [255 255   0]]]
460 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 2

60 
 [[[149 125  99]
  [151 127 101]
  [154 130 104]
  ...
  [152 133 109]
  [149 131 107]
  [147 129 105]]

 [[149 125  99]
  [150 126 100]
  [154 130 104]
  ...
  [154 135 111]
  [149 131 107]
  [147 129 105]]

 [[147 123  97]
  [153 129 103]
  [158 134 108]
  ...
  [157 138 114]
  [154 136 112]
  [148 130 106]]

 ...

 [[143 117 105]
  [144 118 107]
  [149 123 112]
  ...
  [149 122 113]
  [147 120 111]
  [156 129 120]]

 [[155 127 113]
  [156 128 114]
  [165 137 123]
  ...
  [161 133 121]
  [153 125 112]
  [168 140 128]]

 [[168 140 126]
  [180 152 138]
  [175 147 133]
  ...
  [169 141 129]
  [169 141 129]
  [166 138 126]]]
70 
 [[[247 240 222]
  [247 240 222]
  [247 240 222]
  ...
  [247 240 222]
  [247 240 222]
  [247 240 222]]

 [[247 240 222]
  [247 240 222]
  [247 240 222]
  ...
  [247 240 222]
  [247 240 222]
  [247 240 222]]

 [[247 240 222]
  [247 240 222]
  [247 240 222]
  ...
  [247 240 222]
  [247 240 222]
  [247 240 222]]

 ...

 [[205 180 170]
  [216 185 179]
  [220 191

80 
 [[[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 ...

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [204 204 204]
  [204 204 204]
  [204 204 204]]]
90 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [1 1 1]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0

80 
 [[[4 4 4]
  [2 2 2]
  [2 2 2]
  ...
  [3 3 3]
  [3 3 3]
  [4 4 4]]

 [[2 2 2]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [1 1 1]
  [2 2 2]]

 [[2 2 2]
  [1 1 1]
  [1 1 1]
  ...
  [0 0 0]
  [0 0 0]
  [2 2 2]]

 ...

 [[2 4 2]
  [3 1 1]
  [2 4 4]
  ...
  [7 5 3]
  [1 2 2]
  [2 2 4]]

 [[2 2 2]
  [1 1 1]
  [1 1 1]
  ...
  [3 2 2]
  [1 0 0]
  [2 2 2]]

 [[3 3 3]
  [2 2 2]
  [2 2 2]
  ...
  [2 1 2]
  [2 2 2]
  [3 3 3]]]
0 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [247 247 247]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [247 247 247]]

 [[254 254 254]
  [254 254 254]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [247 247 247]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [247 247 247]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [247 247 247]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  .

40 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
0 
 [[[243 235 202]
  [243 234 197]
  [242 231 198]
  ...
  [247 236 215]
  [250 241 218]
  [252 242 219]]

 [[232 223 190]
  [235 224 186]
  [208 194 160]
  ...
  [250 233 209]
  [250 233 206]
  [246 229 203]]

 [[221 211 177]
  [206 195 156]
  [197 182 147]
  ...
  [254 232 204]
  [254 233 201]
  [252 231 199]]

 ...

 [[219 200  83]
  [207 176  36]
  [194 167 

0 
 [[[154 158 156]
  [112 126 114]
  [119 132 121]
  ...
  [ 68  83  92]
  [ 65  82  92]
  [ 58  77  90]]

 [[155 159 157]
  [114 128 116]
  [121 134 123]
  ...
  [ 71  87  96]
  [ 70  87  98]
  [ 63  81  94]]

 [[153 158 156]
  [117 131 118]
  [125 138 127]
  ...
  [ 75  91 100]
  [ 70  88  98]
  [ 64  82  95]]

 ...

 [[ 95  91  89]
  [  6   2   2]
  [  8   3   7]
  ...
  [141 160 158]
  [135 155 153]
  [132 152 150]]

 [[102  98  97]
  [  4   1   1]
  [  9   4   8]
  ...
  [139 158 157]
  [136 156 154]
  [131 151 149]]

 [[ 99  95  93]
  [  8   4   4]
  [ 10   6   9]
  ...
  [136 155 153]
  [135 155 153]
  [133 153 151]]]
10 
 [[[156 154 167]
  [158 156 169]
  [160 158 171]
  ...
  [152 150 170]
  [151 150 167]
  [150 149 167]]

 [[156 154 167]
  [158 156 169]
  [160 158 171]
  ...
  [151 150 169]
  [149 148 166]
  [148 147 165]]

 [[156 154 167]
  [158 156 169]
  [159 157 170]
  ...
  [151 150 168]
  [150 149 167]
  [148 147 165]]

 ...

 [[122 101 108]
  [124 103 110]
  [126 105 

0 
 [[[102 122 131]
  [105 125 134]
  [ 96 116 125]
  ...
  [ 86  96 101]
  [ 93 106 110]
  [ 98 118 123]]

 [[102 122 131]
  [ 96 116 125]
  [106 127 136]
  ...
  [ 92 105 111]
  [ 98 113 119]
  [ 86 104 111]]

 [[110 130 139]
  [102 122 131]
  [105 126 135]
  ...
  [ 98 115 122]
  [ 90 107 115]
  [ 99 116 126]]

 ...

 [[103 104  81]
  [107 109 103]
  [109 122 135]
  ...
  [244 245 242]
  [242 243 238]
  [226 227 222]]

 [[ 97  99  74]
  [ 93  96  87]
  [100 113 122]
  ...
  [219 220 217]
  [219 219 214]
  [230 230 226]]

 [[ 93  95  68]
  [ 84  87  75]
  [ 94 108 115]
  ...
  [201 202 199]
  [220 221 216]
  [217 218 213]]]
10 
 [[[194 179 148]
  [194 179 147]
  [190 175 143]
  ...
  [ 88  83  64]
  [ 98  95  73]
  [125 123  99]]

 [[204 190 155]
  [198 184 149]
  [201 187 152]
  ...
  [ 92  90  72]
  [ 97  96  75]
  [112 112  90]]

 [[189 173 145]
  [178 163 134]
  [175 160 132]
  ...
  [ 84  84  68]
  [ 96  96  77]
  [103 105  87]]

 ...

 [[ 89  79  87]
  [ 92  83  91]
  [ 80  71 

10 
 [[[ 89 147 161]
  [ 83 149 161]
  [ 82 148 159]
  ...
  [102 155 169]
  [103 156 170]
  [106 159 173]]

 [[ 87 145 159]
  [ 83 149 161]
  [ 84 150 161]
  ...
  [105 158 172]
  [102 155 169]
  [100 153 167]]

 [[ 94 152 166]
  [ 90 157 168]
  [ 88 153 165]
  ...
  [106 159 173]
  [109 162 176]
  [105 158 172]]

 ...

 [[ 85 143 154]
  [ 80 141 151]
  [ 79 143 153]
  ...
  [ 94 153 167]
  [ 91 150 164]
  [ 90 150 164]]

 [[ 84 142 154]
  [ 83 143 154]
  [ 80 144 154]
  ...
  [ 94 153 166]
  [ 91 150 164]
  [ 91 150 164]]

 [[ 84 142 154]
  [ 85 145 156]
  [ 82 145 155]
  ...
  [ 92 151 165]
  [ 91 150 164]
  [ 93 152 166]]]
20 
 [[[119  96  72]
  [121  96  69]
  [122  91  62]
  ...
  [ 78  66  20]
  [ 25  44   3]
  [  8  19   2]]

 [[154 142 128]
  [165 154 138]
  [170 162 142]
  ...
  [ 64  57  12]
  [ 17  40   3]
  [  3  14   2]]

 [[141 121 104]
  [160 145 126]
  [191 184 162]
  ...
  [ 69  63  20]
  [ 12  34   4]
  [  0   6   2]]

 ...

 [[ 66  45  46]
  [ 64  44  48]
  [ 50  33

50 
 [[[200 205 199]
  [200 205 199]
  [200 205 199]
  ...
  [202 204 199]
  [202 204 199]
  [202 204 199]]

 [[200 205 199]
  [200 205 199]
  [200 205 199]
  ...
  [202 204 199]
  [202 204 199]
  [202 204 199]]

 [[203 208 202]
  [201 206 200]
  [200 205 199]
  ...
  [201 203 198]
  [201 203 198]
  [201 203 198]]

 ...

 [[220 225 221]
  [219 224 220]
  [218 223 219]
  ...
  [232 238 236]
  [232 238 236]
  [232 238 236]]

 [[223 228 224]
  [222 227 223]
  [221 226 222]
  ...
  [232 238 236]
  [232 238 236]
  [232 238 236]]

 [[224 229 225]
  [224 229 225]
  [224 229 225]
  ...
  [232 238 236]
  [232 238 236]
  [232 238 236]]]
0 
 [[[245 245 245]
  [245 245 245]
  [245 245 245]
  ...
  [245 245 245]
  [245 245 245]
  [247 247 247]]

 [[245 245 245]
  [245 245 245]
  [245 245 245]
  ...
  [245 245 245]
  [245 245 245]
  [245 245 245]]

 [[245 245 245]
  [245 245 245]
  [245 245 245]
  ...
  [245 245 245]
  [244 244 244]
  [244 244 244]]

 ...

 [[245 245 245]
  [245 245 245]
  [245 245 

10 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
20 
 [[[ 10 119 222]
  [ 10 119 222]
  [ 10 119 222]
  ...
  [ 10 119 222]
  [ 10 119 222]
  [ 10 119 222]]

 [[ 10 119 222]
  [ 10 119 222]
  [ 10 119 222]
  ...
  [ 10 119 222]
  [ 10 119 222]
  [ 10 119 222]]

 [[ 11 117 222]
  [ 11 117 222]
  [ 11 117 222]
  ...
  [ 11 117 222]
  [ 11 117 222]
  [ 11 117 222]]

 ...

 [[ 17  94 198]
  [ 17  94 198]
  [ 17  94 198]
  ...
  [ 17  94 198]
  [ 17  94 198]
  [ 17  94 198]]

 [[ 19  96 200]
  [ 19  96 200]
  [ 19  96 200]
  ...
  [ 19  96 200]
  [ 19  96 200]
  [ 19  96 200]]

 [[ 18  95 199]
  [ 18  95 199]
  [ 18  95 199]
  

20 
 [[[144 138 115]
  [140 133 116]
  [116 107  98]
  ...
  [168 150 130]
  [156 139 123]
  [160 143 131]]

 [[129 122 101]
  [129 122 105]
  [110 102  91]
  ...
  [160 147 126]
  [159 144 127]
  [164 149 134]]

 [[107 100  83]
  [124 117 101]
  [117 109  96]
  ...
  [147 140 116]
  [156 146 124]
  [161 147 126]]

 ...

 [[171 160 142]
  [170 161 145]
  [159 153 137]
  ...
  [174 164 155]
  [179 171 162]
  [187 180 173]]

 [[173 162 145]
  [163 154 138]
  [166 159 146]
  ...
  [187 177 169]
  [182 173 165]
  [174 165 160]]

 [[165 154 137]
  [163 154 139]
  [187 180 166]
  ...
  [184 174 166]
  [174 165 157]
  [163 154 149]]]
30 
 [[[ 78  79  91]
  [ 73  72  86]
  [ 75  72  86]
  ...
  [ 99  81 103]
  [101  85 105]
  [155 143 160]]

 [[ 96  76  87]
  [ 96  74  85]
  [102  77  89]
  ...
  [109  80 106]
  [106  76 101]
  [152 127 148]]

 [[111  73  85]
  [115  75  88]
  [114  72  86]
  ...
  [ 53  45  64]
  [ 57  46  64]
  [116 109 123]]

 ...

 [[193 167 152]
  [206 180 165]
  [210 184

40 
 [[[ 61   2   2]
  [ 62   5   9]
  [ 61   7  13]
  ...
  [ 52   9   7]
  [ 58   6   8]
  [ 67   1   8]]

 [[ 54   1   1]
  [104  66  64]
  [128 108 105]
  ...
  [ 92  81  74]
  [ 79  44  42]
  [ 58   0   2]]

 [[ 54   1   0]
  [101  73  68]
  [125 125 119]
  ...
  [ 91  93  91]
  [ 82  52  47]
  [ 57   0   0]]

 ...

 [[ 54   1   0]
  [ 88  60  63]
  [106 104 108]
  ...
  [ 86  81  86]
  [ 81  45  47]
  [ 59   0   0]]

 [[ 59   0   1]
  [ 86  48  53]
  [109  91  97]
  ...
  [ 90  72  77]
  [ 77  41  40]
  [ 56   1   1]]

 [[ 64   0   2]
  [ 59   6   7]
  [ 55   9  11]
  ...
  [ 65   7  11]
  [ 62   4   4]
  [ 63   1   2]]]
50 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 66  64  10]
  [ 63  59   8]
  [ 65  60

110 
 [[[ 63  64  82]
  [ 66  67  83]
  [ 67  69  87]
  ...
  [  0   0   4]
  [  7   8  12]
  [ 72  85 105]]

 [[ 64  64  83]
  [ 66  67  83]
  [ 68  70  88]
  ...
  [  0   1   5]
  [  7   8  12]
  [ 92 105 123]]

 [[ 64  65  83]
  [ 67  68  86]
  [ 69  70  89]
  ...
  [  0   0   5]
  [  9   9  14]
  [ 97 107 123]]

 ...

 [[ 52  63  68]
  [ 54  66  70]
  [ 53  66  71]
  ...
  [ 62  65  60]
  [ 61  63  57]
  [ 60  61  58]]

 [[ 53  64  70]
  [ 55  65  72]
  [ 55  64  71]
  ...
  [ 75  93  86]
  [ 69  83  79]
  [ 66  73  68]]

 [[ 50  61  67]
  [ 54  63  70]
  [ 54  62  70]
  ...
  [ 69  89  87]
  [ 81 109 103]
  [ 86 109 101]]]
120 
 [[[29 28 25]
  [29 28 25]
  [36 35 31]
  ...
  [30 29 14]
  [17 19 15]
  [ 7  6  6]]

 [[ 4 13 14]
  [ 5 12 12]
  [24 23 23]
  ...
  [34 30 17]
  [16 14  9]
  [24 21 13]]

 [[ 8 16 14]
  [ 8 15 13]
  [25 24 20]
  ...
  [37 30 17]
  [19 16  9]
  [32 28 13]]

 ...

 [[ 5  2  6]
  [ 4  1  5]
  [ 4  2  3]
  ...
  [19 15 11]
  [35 30 22]
  [33 26 16]]

 [[ 8  3

310 
 [[[ 51  63  48]
  [ 54  66  56]
  [ 55  67  59]
  ...
  [ 56 113 129]
  [ 59 113 129]
  [ 56  91  99]]

 [[ 55  64  55]
  [ 52  61  55]
  [ 44  52  48]
  ...
  [ 61 118 133]
  [ 64 119 134]
  [ 60  96 103]]

 [[ 39  44  42]
  [ 37  41  42]
  [ 40  47  50]
  ...
  [ 62 119 134]
  [ 63 118 133]
  [ 61  96 103]]

 ...

 [[ 36  55  53]
  [ 36  55  53]
  [ 38  54  53]
  ...
  [ 75 132 144]
  [ 72 117 124]
  [ 69 110 113]]

 [[ 36  55  53]
  [ 36  55  53]
  [ 39  55  54]
  ...
  [ 76 133 145]
  [ 72 117 124]
  [ 70 110 115]]

 [[ 34  53  51]
  [ 36  52  51]
  [ 38  53  51]
  ...
  [ 72 129 141]
  [ 71 111 120]
  [ 67 104 112]]]
320 
 [[[227 226 219]
  [231 231 223]
  [230 232 221]
  ...
  [ 74 105 102]
  [161 191 194]
  [170 195 203]]

 [[238 238 228]
  [247 247 240]
  [250 251 246]
  ...
  [110 143 148]
  [169 199 204]
  [191 214 215]]

 [[226 227 213]
  [239 239 233]
  [249 251 245]
  ...
  [200 225 231]
  [132 155 153]
  [184 199 195]]

 ...

 [[ 22  39  35]
  [ 23  39  35]
  [ 28  

30 
 [[[178 147  90]
  [178 149  93]
  [176 150  97]
  ...
  [200 221 201]
  [202 224 205]
  [203 224 206]]

 [[184 166 119]
  [186 163 113]
  [184 156 101]
  ...
  [209 231 210]
  [210 231 211]
  [207 228 208]]

 [[227 236 232]
  [225 231 224]
  [220 221 210]
  ...
  [206 228 207]
  [208 230 208]
  [206 228 206]]

 ...

 [[195 218 221]
  [197 220 222]
  [193 216 218]
  ...
  [185 204 198]
  [117 127 130]
  [ 39  49  61]]

 [[186 206 208]
  [176 196 199]
  [173 194 196]
  ...
  [190 214 208]
  [200 217 207]
  [178 194 187]]

 [[166 184 188]
  [166 185 189]
  [166 188 191]
  ...
  [185 206 201]
  [185 207 197]
  [185 205 198]]]
40 
 [[[ 76  76  69]
  [ 76  76  69]
  [ 77  76  70]
  ...
  [121 125 111]
  [121 125 111]
  [117 122 107]]

 [[ 82  82  69]
  [ 82  83  70]
  [ 84  84  71]
  ...
  [139 145 118]
  [139 145 118]
  [136 143 117]]

 [[ 52  52  43]
  [ 53  52  43]
  [ 61  61  52]
  ...
  [156 163 130]
  [155 161 129]
  [152 160 127]]

 ...

 [[ 69  83  58]
  [104 113  77]
  [ 98  98

260 
 [[[ 82 104 118]
  [ 83 105 121]
  [ 85 106 125]
  ...
  [ 97 130 174]
  [ 97 130 173]
  [ 96 129 172]]

 [[ 88 110 126]
  [ 89 110 128]
  [ 89 110 132]
  ...
  [102 134 183]
  [102 134 183]
  [101 133 182]]

 [[ 91 112 132]
  [ 91 112 133]
  [ 90 110 135]
  ...
  [103 136 181]
  [103 136 181]
  [102 135 180]]

 ...

 [[ 96 128 150]
  [ 68  97 119]
  [ 51  74  97]
  ...
  [ 34  52  84]
  [ 33  49  79]
  [ 35  51  78]]

 [[ 46  66  93]
  [ 44  65  90]
  [ 44  65  89]
  ...
  [ 36  51  83]
  [ 34  49  78]
  [ 34  50  77]]

 [[ 47  65  92]
  [ 49  66  93]
  [ 48  66  90]
  ...
  [ 36  50  82]
  [ 34  49  79]
  [ 31  47  73]]]
270 
 [[[125 131 127]
  [125 131 127]
  [127 133 129]
  ...
  [ 71  42  30]
  [ 70  44  27]
  [ 72  47  27]]

 [[124 130 126]
  [126 132 128]
  [127 133 129]
  ...
  [ 65  37  21]
  [ 68  36  19]
  [ 69  36  20]]

 [[126 132 127]
  [127 133 129]
  [125 131 127]
  ...
  [ 55  34  20]
  [ 56  34  22]
  [ 57  35  25]]

 ...

 [[209 215 215]
  [212 218 218]
  [215 2

20 
 [[[249 254 254]
  [255 251 253]
  [247 250 248]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[253 250 243]
  [252 253 255]
  [237 252 253]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[250 250 248]
  [253 253 252]
  [240 248 237]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
30 
 [[[236 234 213]
  [239 236 211]
  [243 238 214]
  ...
  [237 242 213]
  [240 236 209]
  [239 231 215]]

 [[237 237 210]
  [230 220 197]
  [212 196 148]
  ...
  [206 194 149]
  [232 219 194]
  [242 233 213]]

 [[239 240 214]
  [217 204 145]
  [198 172  70]
  ...
  [190 163  82]
  [228 217 168]
  [239 239 205]]

 ...

 [[241 240 214]
  [218 210 141]
  [191 168

0 
 [[[117 102  87]
  [100  84  62]
  [ 84  65  48]
  ...
  [ 99 102  79]
  [135 129  99]
  [151 139 100]]

 [[127 111  95]
  [ 74  55  38]
  [ 75  54  39]
  ...
  [110 117  87]
  [138 138 104]
  [149 142 104]]

 [[109  91  73]
  [ 88  66  54]
  [ 96  72  58]
  ...
  [110 111  78]
  [139 141  99]
  [148 149 100]]

 ...

 [[217 173 131]
  [219 178 135]
  [206 169 124]
  ...
  [111 110  83]
  [ 95  97  77]
  [ 87  85  69]]

 [[226 183 144]
  [212 169 127]
  [202 159 114]
  ...
  [105  87  71]
  [ 78  66  56]
  [ 67  53  50]]

 [[236 202 159]
  [226 181 136]
  [218 161 112]
  ...
  [ 86  52  42]
  [ 78  54  40]
  [ 84  62  50]]]
10 
 [[[ 12  19   3]
  [ 14  21   5]
  [ 14  21   5]
  ...
  [ 27  28  10]
  [ 79  67  31]
  [ 66  57  24]]

 [[ 13  20   4]
  [ 13  20   4]
  [ 13  20   4]
  ...
  [ 37  33  12]
  [ 80  68  36]
  [ 53  45  19]]

 [[ 12  19   3]
  [ 12  19   3]
  [ 12  19   3]
  ...
  [ 71  59  31]
  [ 84  73  40]
  [ 42  37  12]]

 ...

 [[ 98 105  92]
  [106 109  99]
  [ 90  85 

40 
 [[[162 163 167]
  [162 163 167]
  [162 163 167]
  ...
  [124 123 128]
  [120 119 124]
  [116 115 120]]

 [[167 168 172]
  [167 168 172]
  [167 168 172]
  ...
  [130 129 134]
  [125 124 129]
  [121 120 125]]

 [[170 171 175]
  [170 171 175]
  [170 171 175]
  ...
  [134 133 138]
  [131 130 135]
  [125 124 129]]

 ...

 [[246 248 247]
  [246 248 247]
  [246 248 247]
  ...
  [251 251 251]
  [252 252 252]
  [252 252 252]]

 [[246 248 247]
  [246 248 247]
  [246 248 247]
  ...
  [251 251 251]
  [251 251 251]
  [251 251 251]]

 [[246 248 247]
  [246 248 247]
  [246 248 247]
  ...
  [250 250 250]
  [247 247 247]
  [245 245 245]]]
50 
 [[[150 169 167]
  [149 168 166]
  [149 168 166]
  ...
  [109 125 124]
  [104 120 119]
  [ 99 115 114]]

 [[154 173 171]
  [153 172 170]
  [152 171 169]
  ...
  [113 129 128]
  [109 125 124]
  [106 122 121]]

 [[157 176 174]
  [157 176 174]
  [157 176 174]
  ...
  [119 135 134]
  [115 131 130]
  [111 127 126]]

 ...

 [[245 249 250]
  [245 249 250]
  [245 249

0 
 [[[140 156 189]
  [134 150 183]
  [123 139 172]
  ...
  [113 132 168]
  [117 136 169]
  [115 134 167]]

 [[140 156 189]
  [145 161 194]
  [137 153 186]
  ...
  [112 131 167]
  [113 131 165]
  [115 133 167]]

 [[142 158 191]
  [141 157 190]
  [135 151 184]
  ...
  [112 131 169]
  [113 130 167]
  [113 131 168]]

 ...

 [[129 138 131]
  [120 130 123]
  [132 142 135]
  ...
  [140 147 141]
  [140 146 141]
  [139 146 138]]

 [[125 135 127]
  [119 129 121]
  [130 140 132]
  ...
  [138 147 140]
  [140 148 139]
  [140 149 138]]

 [[123 132 123]
  [120 128 120]
  [131 140 132]
  ...
  [134 146 137]
  [136 147 136]
  [135 146 133]]]
10 
 [[[ 79  82  83]
  [ 82  87  82]
  [107 116 103]
  ...
  [ 32  42  53]
  [ 38  47  56]
  [ 27  30  38]]

 [[124 111 107]
  [107 101  92]
  [103 105  93]
  ...
  [ 39  51  60]
  [ 46  55  62]
  [ 38  42  48]]

 [[141 130 117]
  [173 171 156]
  [128 139 123]
  ...
  [ 39  48  55]
  [ 43  50  56]
  [ 34  39  43]]

 ...

 [[153 131 107]
  [193 169 136]
  [184 173 

60 
 [[[ 84  89  47]
  [ 90  93  53]
  [ 94  94  55]
  ...
  [ 63  69  58]
  [104 107  95]
  [ 93  96  83]]

 [[141 151 103]
  [ 82  90  46]
  [ 66  71  30]
  ...
  [ 51  62  44]
  [ 88  93  73]
  [ 78  76  60]]

 [[133 140  94]
  [ 81  85  46]
  [ 58  58  30]
  ...
  [ 72  79  51]
  [ 95  96  68]
  [ 95  89  68]]

 ...

 [[ 60  47  36]
  [ 68  61  48]
  [ 73  63  52]
  ...
  [ 41  31  17]
  [ 42  33  19]
  [ 71  61  50]]

 [[ 80  69  60]
  [ 83  77  66]
  [ 81  71  62]
  ...
  [ 62  51  35]
  [ 49  37  21]
  [ 40  28  15]]

 [[ 83  71  65]
  [ 72  66  59]
  [ 65  57  44]
  ...
  [ 69  57  42]
  [ 66  54  40]
  [ 59  47  35]]]
70 
 [[[205 187 126]
  [208 172  98]
  [215 173 105]
  ...
  [185 150  95]
  [180 146  94]
  [185 166 120]]

 [[209 162  70]
  [208 142  25]
  [215 142  25]
  ...
  [176 112   8]
  [171 108  13]
  [175 134  75]]

 [[201 163  78]
  [202 147  26]
  [209 148  25]
  ...
  [178 115  16]
  [177 109  14]
  [175 135  67]]

 ...

 [[219 194 100]
  [223 181  55]
  [225 187

40 
 [[[ 44  89 144]
  [ 43  88 143]
  [ 43  88 143]
  ...
  [ 49  91 149]
  [ 49  91 149]
  [ 49  91 149]]

 [[ 42  87 142]
  [ 43  88 143]
  [ 44  89 144]
  ...
  [ 51  93 151]
  [ 51  93 151]
  [ 50  92 150]]

 [[ 43  88 143]
  [ 43  88 143]
  [ 44  89 144]
  ...
  [ 51  93 151]
  [ 51  93 151]
  [ 50  92 150]]

 ...

 [[ 12  41  64]
  [ 20  49  72]
  [ 11  40  64]
  ...
  [ 26  45  76]
  [ 25  44  75]
  [ 27  46  78]]

 [[ 24  47  74]
  [ 26  50  75]
  [ 19  43  68]
  ...
  [ 39  59  91]
  [ 28  48  80]
  [ 25  45  77]]

 [[ 18  44  71]
  [ 13  39  66]
  [ 23  49  77]
  ...
  [ 21  41  73]
  [ 20  41  72]
  [ 18  39  70]]]
50 
 [[[ 26  88 149]
  [ 26  88 149]
  [ 26  88 149]
  ...
  [ 43  93 152]
  [ 42  92 151]
  [ 43  93 152]]

 [[ 26  88 149]
  [ 26  88 149]
  [ 26  88 149]
  ...
  [ 43  93 152]
  [ 44  94 153]
  [ 42  92 151]]

 [[ 27  87 149]
  [ 27  87 149]
  [ 27  87 149]
  ...
  [ 44  94 153]
  [ 44  94 153]
  [ 44  94 153]]

 ...

 [[ 37  66  90]
  [ 38  63  89]
  [ 42  64

60 
 [[[ 78  64  63]
  [ 85  66  57]
  [142 111  89]
  ...
  [123  62  61]
  [120  61  60]
  [119  61  59]]

 [[ 77  64  64]
  [ 85  65  58]
  [145 114  95]
  ...
  [122  61  60]
  [120  60  59]
  [119  61  59]]

 [[ 78  64  68]
  [ 87  66  62]
  [137 106  89]
  ...
  [123  63  62]
  [121  61  60]
  [119  61  59]]

 ...

 [[141 120  98]
  [141 115 101]
  [146 113 100]
  ...
  [135  65  68]
  [135  65  68]
  [134  64  67]]

 [[130 111  87]
  [133 110  92]
  [136 110  91]
  ...
  [131  63  66]
  [130  63  66]
  [130  63  66]]

 [[ 85  71  70]
  [ 84  69  69]
  [ 84  69  67]
  ...
  [128  64  65]
  [127  63  64]
  [127  63  64]]]
0 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 

80 
 [[[  2   4   5]
  [  5   4   1]
  [ 13   6   2]
  ...
  [ 16   5   3]
  [ 11   4   1]
  [  0   3   8]]

 [[  1   4   1]
  [ 20  18   4]
  [ 87  81  58]
  ...
  [120 104  83]
  [102  90  70]
  [ 20  22  15]]

 [[  2   2   0]
  [ 33  30   6]
  [112 105  65]
  ...
  [142 121  81]
  [144 127  89]
  [ 43  41  26]]

 ...

 [[  1   0   0]
  [ 78  72  47]
  [161 143 108]
  ...
  [186 151  96]
  [182 154 111]
  [ 50  42  31]]

 [[  0   2   2]
  [ 63  60  38]
  [158 142 113]
  ...
  [185 150 107]
  [178 150 118]
  [ 51  43  34]]

 [[  1   6   4]
  [ 25  24  10]
  [ 79  65  50]
  ...
  [114  79  61]
  [103  76  63]
  [ 28  21  19]]]
90 
 [[[  3   1   8]
  [  4   2   4]
  [  3   2   0]
  ...
  [  4  21   2]
  [  3  12   2]
  [  4   2   5]]

 [[  3   1   6]
  [ 18  16  15]
  [ 32  32  24]
  ...
  [ 85 113  46]
  [ 61  77  40]
  [  5   7   3]]

 [[  3   1   2]
  [ 23  22  17]
  [ 40  41  28]
  ...
  [110 147  29]
  [ 87 109  43]
  [ 14  20   9]]

 ...

 [[ 14   9   8]
  [ 91  84  59]
  [ 94  80

70 
 [[[ 67  77  74]
  [ 50  47  32]
  [114 110  94]
  ...
  [172 171 177]
  [141 148 150]
  [184 172 168]]

 [[ 62  70  63]
  [ 63  61  46]
  [111 106  90]
  ...
  [161 164 172]
  [121 124 126]
  [128 112 106]]

 [[ 54  57  46]
  [ 53  52  40]
  [ 69  63  46]
  ...
  [147 156 162]
  [148 145 155]
  [146 122 133]]

 ...

 [[174 156 110]
  [130 104  61]
  [180 149 107]
  ...
  [211 179 134]
  [183 148 109]
  [228 197 157]]

 [[147 130  84]
  [154 133  88]
  [170 143 101]
  ...
  [206 175 126]
  [149 117  78]
  [190 161 120]]

 [[126 109  64]
  [172 155 109]
  [169 150 105]
  ...
  [180 151  96]
  [182 154 106]
  [185 160 111]]]
0 
 [[[129 129 129]
  [129 129 129]
  [129 129 129]
  ...
  [129 129 129]
  [129 129 129]
  [129 129 129]]

 [[129 129 129]
  [129 129 129]
  [129 129 129]
  ...
  [129 129 129]
  [129 129 129]
  [129 129 129]]

 [[129 129 129]
  [129 129 129]
  [129 129 129]
  ...
  [129 129 129]
  [129 129 129]
  [129 129 129]]

 ...

 [[129 129 129]
  [129 129 129]
  [129 129 

20 
 [[[ 24 116 140]
  [ 24 115 142]
  [ 31 122 152]
  ...
  [ 70 178 217]
  [ 76 184 222]
  [ 77 185 223]]

 [[ 21 113 139]
  [ 26 117 145]
  [ 28 118 150]
  ...
  [ 72 179 218]
  [ 76 184 222]
  [ 74 182 220]]

 [[ 27 118 145]
  [ 29 120 150]
  [ 36 126 160]
  ...
  [ 74 179 218]
  [ 77 186 224]
  [ 74 182 220]]

 ...

 [[  4  57  96]
  [  5  56  95]
  [ 10  58  99]
  ...
  [ 39 161 208]
  [ 44 156 205]
  [ 23  84 151]]

 [[ 11  63  97]
  [ 14  67 101]
  [  9  63  97]
  ...
  [ 34 163 199]
  [ 39 155 200]
  [ 19  78 141]]

 [[  8  58  92]
  [ 13  66 100]
  [  6  59  93]
  ...
  [ 40 168 205]
  [ 48 164 209]
  [ 17  76 139]]]
30 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [4 4 2]
  [1 1 1]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [6 3 4]
  [1 1 1]
  [0 0 0]]

 [[0 0 0]
  [0

80 
 [[[112  94  82]
  [110  92  80]
  [110  92  80]
  ...
  [ 44  39  35]
  [ 42  37  33]
  [ 44  39  35]]

 [[112  94  82]
  [110  92  80]
  [110  92  80]
  ...
  [ 47  42  38]
  [ 44  39  35]
  [ 44  39  35]]

 [[112  94  82]
  [111  93  81]
  [109  91  79]
  ...
  [ 43  38  34]
  [ 40  35  31]
  [ 42  37  33]]

 ...

 [[219 190 158]
  [218 189 157]
  [219 190 158]
  ...
  [220 194 173]
  [225 199 177]
  [228 202 181]]

 [[219 190 158]
  [220 191 159]
  [220 191 159]
  ...
  [217 191 169]
  [220 195 173]
  [222 197 175]]

 [[219 190 158]
  [220 191 159]
  [218 189 157]
  ...
  [214 188 166]
  [214 189 167]
  [217 192 170]]]
0 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 

40 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 254]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 254]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 254]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
50 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255

  [255 255 255]]]
220 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
230 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 252]
  [255 255 254]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 253]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [254 255 253]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255

390 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
400 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 2

580 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
590 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 2

770 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
780 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 2

30 
 [[[ 17  16  15]
  [ 40  30  30]
  [ 24  20  24]
  ...
  [ 46  41  39]
  [ 37  34  35]
  [ 33  33  33]]

 [[ 53  39  41]
  [152 128 131]
  [ 98  80  88]
  ...
  [124 110 110]
  [137 125 131]
  [119 110 114]]

 [[ 35  29  39]
  [132 115 126]
  [ 87  78  94]
  ...
  [ 33  15  25]
  [ 95  77  87]
  [121 106 116]]

 ...

 [[ 65  52  56]
  [212 190 188]
  [172 147 140]
  ...
  [230 234 226]
  [227 231 226]
  [247 248 242]]

 [[ 68  60  61]
  [209 191 192]
  [140 120 114]
  ...
  [223 222 218]
  [209 208 205]
  [221 220 216]]

 [[ 15  14  19]
  [ 45  37  41]
  [ 35  27  29]
  ...
  [ 44  43  43]
  [ 43  41  41]
  [ 40  38  36]]]
0 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 

40 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
50 
 [[[ 19  23  21]
  [ 35  51  57]
  [ 35  49  53]
  ...
  [ 36  48  49]
  [ 37  45  52]
  [ 14  10  15]]

 [[ 38  48  49]
  [ 87 120 129]
  [ 81 121 126]
  ...
  [ 83 120 123]
  [ 86 112 118]
  [ 20  24  33]]

 [[ 39  43  44]
  [ 86 118 127]
  [ 77 120 126]
  ...
  [ 81 120 125]
  [ 78 115 114]
  [ 19  26  30]]

 ...

 [[ 35  39  31]
  [ 94  99  73]
  [ 89  96

50 
 [[[ 47  47  31]
  [ 75  62  51]
  [ 77  63  54]
  ...
  [ 50  91  90]
  [ 64 103 105]
  [ 48  86  94]]

 [[104  79  58]
  [124  93  73]
  [119  89  68]
  ...
  [ 54  93  91]
  [ 69 107 109]
  [ 58  95 102]]

 [[103  72  57]
  [114  82  65]
  [103  72  52]
  ...
  [ 58  93  89]
  [ 58  94  95]
  [ 59  93  99]]

 ...

 [[ 33  41  27]
  [ 26  51  25]
  [ 70 104  67]
  ...
  [ 84 109  92]
  [ 81 106  91]
  [ 78 103  84]]

 [[ 72  79  57]
  [ 87 111  80]
  [ 86 117  80]
  ...
  [ 85 112  93]
  [ 88 116  98]
  [ 70  96  77]]

 [[106 119  76]
  [ 99 122  82]
  [104 132  95]
  ...
  [ 80 107  86]
  [ 76 106  83]
  [ 75 104  82]]]
0 
 [[[100 105  51]
  [130 125  64]
  [142 132  69]
  ...
  [190 208 196]
  [191 209 197]
  [192 210 198]]

 [[ 87  95  46]
  [111 111  56]
  [127 119  55]
  ...
  [197 215 203]
  [193 211 199]
  [193 211 199]]

 [[ 93  92  52]
  [ 85  87  45]
  [105 105  54]
  ...
  [199 216 204]
  [197 215 203]
  [195 213 201]]

 ...

 [[ 62  57  28]
  [ 61  52  27]
  [ 73  51 

50 
 [[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[11 11 11]
  [ 1  1  1]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]
60 
 [[[ 87 101  76]
  [100 111  89]
  [105 115  81]
  ...
  [113 112  86]
  [129 136 111]
  [100 114 109]]

 [[ 71  84  64]
  [115 126 108]
  [101 109  83]
  ...
  [ 86  86  66]
  [110 116  95]
  [128 143 133]]

 [[ 75  86  73]
  [ 67  77  63]
  [ 73  80  62]
  ...
  [104 104  89]
  [ 84  89  74]
  [112 128 111]]

 ...

 [[220 222 183]
  [219 221 184]
  [160 161 126]
  ...
  [103 104  70]
  [ 70  75  40]
  [ 75  80  56]]

 [[221 223 184]
  [206 208 172]
  [146 147 117

10 
 [[[188 195 188]
  [227 231 228]
  [232 232 235]
  ...
  [246 246 245]
  [217 217 217]
  [193 193 193]]

 [[198 202 199]
  [220 221 220]
  [241 240 242]
  ...
  [250 250 248]
  [212 212 212]
  [191 191 191]]

 [[195 195 198]
  [241 240 241]
  [254 250 249]
  ...
  [240 240 237]
  [226 226 226]
  [193 193 193]]

 ...

 [[206 205 208]
  [248 248 246]
  [243 239 235]
  ...
  [213 215 206]
  [229 230 227]
  [202 202 204]]

 [[194 194 193]
  [214 213 211]
  [250 246 244]
  ...
  [239 240 236]
  [239 239 238]
  [202 202 202]]

 [[197 197 196]
  [199 199 198]
  [224 224 223]
  ...
  [210 210 209]
  [202 202 202]
  [195 195 195]]]
20 
 [[[ 1 63  0]
  [ 1 63  0]
  [ 1 63  0]
  ...
  [ 1 63  0]
  [ 1 63  0]
  [ 1 63  0]]

 [[ 1 63  0]
  [ 1 63  0]
  [ 1 63  0]
  ...
  [ 1 63  0]
  [ 1 63  0]
  [ 1 63  0]]

 [[ 1 63  0]
  [ 1 63  0]
  [ 1 63  0]
  ...
  [ 1 63  0]
  [ 1 63  0]
  [ 1 63  0]]

 ...

 [[ 1 63  0]
  [ 1 63  0]
  [ 1 63  0]
  ...
  [ 1 63  0]
  [ 1 63  0]
  [ 1 63  0]]

 [[ 1 63  

30 
 [[[75 75 75]
  [10 10 10]
  [18 18 18]
  ...
  [21 21 21]
  [22 22 22]
  [21 21 21]]

 [[73 73 73]
  [ 9  9  9]
  [16 16 16]
  ...
  [21 21 21]
  [21 21 21]
  [22 22 22]]

 [[70 70 70]
  [10 10 10]
  [15 15 15]
  ...
  [18 18 18]
  [20 20 20]
  [20 20 20]]

 ...

 [[21 21 21]
  [21 21 21]
  [23 23 23]
  ...
  [31 31 31]
  [34 34 34]
  [37 37 37]]

 [[22 22 22]
  [22 22 22]
  [25 25 25]
  ...
  [32 32 32]
  [34 34 34]
  [38 38 38]]

 [[25 25 25]
  [24 24 24]
  [27 27 27]
  ...
  [33 33 33]
  [34 34 34]
  [38 38 38]]]
40 
 [[[255   0 254]
  [255   0 254]
  [255   0 254]
  ...
  [255   0 254]
  [255   0 254]
  [255   0 254]]

 [[255   0 254]
  [255   0 254]
  [255   0 254]
  ...
  [255   0 254]
  [255   0 254]
  [255   0 254]]

 [[255   0 254]
  [255   0 254]
  [255   0 254]
  ...
  [255   0 254]
  [255   0 254]
  [255   0 254]]

 ...

 [[255   0 254]
  [255   0 254]
  [255   0 254]
  ...
  [255   0 254]
  [255   0 254]
  [255   0 254]]

 [[255   0 254]
  [255   0 254]
  [255   0 254

20 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[136 144 136]
  [133 140 130]
  [133 139 128]
  ...
  [214 225 201]
  [204 215 192]
  [200 211 189]]

 [[112 121 118]
  [111 119 112]
  [114 122 112]
  ...
  [196 207 181]
  [195 206 179]
  [205 215 188]]

 [[108 117 114]
  [109 117 110]
  [106 113 104]
  ...
  [222 230 199]
  [228 236 204]
  [229 237 205]]]
30 
 [[[255   0 254]
  [255   0 254]
  [255   0 254]
  ...
  [255   0 254]
  [255   0 254]
  [255   0 254]]

 [[255   0 254]
  [255   0 254]
  [255   0 254]
  ...
  [255   0 254]
  [255   0 254]
  [255   0 254]]

 [[255   0 254]
  [255   0 254]
  [255   0 254]
  ...
  [255   0 254]
  [255   0 254]
  [255   0 254]]

 ...

 [[255   0 254]
  [255   0 254]
  [255   0

40 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
50 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
60 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
 

140 
 [[[205 204 202]
  [167 164 163]
  [170 164 164]
  ...
  [170 165 165]
  [176 170 170]
  [202 197 197]]

 [[169 167 165]
  [114 110 109]
  [121 114 115]
  ...
  [113 107 107]
  [118 112 112]
  [175 170 170]]

 [[187 186 184]
  [136 132 131]
  [129 122 123]
  ...
  [123 117 117]
  [144 138 138]
  [198 193 193]]

 ...

 [[167 167 165]
  [106 101  98]
  [128 120 119]
  ...
  [112 106 102]
  [100  95  91]
  [175 171 168]]

 [[174 173 171]
  [ 95  92  91]
  [108 102 102]
  ...
  [125 120 115]
  [103  97  93]
  [159 155 151]]

 [[200 202 199]
  [159 159 156]
  [162 159 157]
  ...
  [176 177 173]
  [160 160 156]
  [196 196 193]]]
150 
 [[[254 245 216]
  [254 247 219]
  [254 249 223]
  ...
  [254 227 214]
  [255 227 215]
  [255 229 217]]

 [[253 243 222]
  [253 246 220]
  [254 250 218]
  ...
  [255 228 215]
  [255 228 216]
  [255 228 216]]

 [[254 245 220]
  [253 246 219]
  [251 246 218]
  ...
  [254 228 215]
  [255 229 217]
  [255 227 215]]

 ...

 [[238 151 133]
  [254 169 149]
  [255 1

30 
 [[[181 163 147]
  [177 160 144]
  [176 160 144]
  ...
  [148 145 144]
  [143 143 141]
  [143 143 141]]

 [[179 161 146]
  [176 159 143]
  [174 158 142]
  ...
  [149 146 144]
  [144 144 142]
  [144 144 142]]

 [[178 160 144]
  [176 159 143]
  [172 156 140]
  ...
  [148 145 143]
  [144 144 142]
  [144 144 142]]

 ...

 [[111 111 110]
  [111 111 110]
  [111 111 110]
  ...
  [ 83  87  93]
  [ 77  81  86]
  [ 77  80  84]]

 [[114 114 114]
  [114 114 114]
  [113 113 113]
  ...
  [ 85  88  97]
  [ 80  83  90]
  [ 78  81  86]]

 [[108 108 108]
  [109 109 109]
  [110 110 110]
  ...
  [ 79  83  92]
  [ 82  85  92]
  [ 80  83  88]]]
40 
 [[[103  95  94]
  [102  93  91]
  [106  93  91]
  ...
  [ 79  72  66]
  [ 76  71  65]
  [ 74  71  64]]

 [[104  96  94]
  [104  94  93]
  [107  94  92]
  ...
  [ 79  72  66]
  [ 76  71  65]
  [ 74  71  64]]

 [[104  96  94]
  [103  94  92]
  [107  94  91]
  ...
  [ 78  71  65]
  [ 75  70  64]
  [ 75  72  65]]

 ...

 [[242 255 255]
  [240 253 254]
  [244 254

In [12]:
# 학습용과 검증용으로 나눈다.
X_train, X_test, y_train, y_test = train_test_split(X, Y)
# 하나로 합친다.
xy = (X_train, X_test, y_train, y_test)
# 저장한다.
np.save('img/caltech_obj_101.npy', xy)

C:\Users\master16\anaconda\lib\site-packages\numpy\core\_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
