In [1]:
import cv2
import numpy as np

In [2]:
# cascade 파일
face_cascade_name = 'opencv_data/haarcascades/haarcascade_frontalface_alt.xml'
eyes_cascade_name = 'opencv_data/haarcascades/haarcascade_eye_tree_eyeglasses.xml'

In [3]:
# 영상 파일 이름
# file_name = 'opencv_data/video/obama_01.mp4'
# file_name = 'opencv_data/video/son_01.mp4'
file_name = 'opencv_data/video/son_02.mp4'
# file_name = 'opencv_data/video/tedy_01.mp4'

In [4]:
# 영상 데이터를 불러온다.
cap = cv2.VideoCapture(file_name)

In [5]:
# 얼굴을 인식할 수 있는 모델을 생성한다.
face_cascade = cv2.CascadeClassifier()
eyes_cascade = cv2.CascadeClassifier()
# 케스케이드 파일을 로딩한다.
face_cascade.load(cv2.samples.findFile(face_cascade_name))
eyes_cascade.load(cv2.samples.findFile(eyes_cascade_name))

In [6]:
while True :
    # 영상의 다음 프레임을 읽어온다.
    ret, frame = cap.read()
    # 더 이상 읽어온 영상이 없다면 (끝났다면) 중단시킨다.
    if frame is None :
        break
        
    # 추출한 이미지를 그레이 스케일로 변환한다.
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # 그레이 스케일 이미지를 표준화한다.
    frame_gray = cv2.equalizeHist(frame_gray)
    
    # 얼굴을 인식한다.
    faces = face_cascade.detectMultiScale(frame_gray)
    print(faces)
    # 인식된 얼굴의 수 만큼 반복한다.
    for x, y, w, h in faces :
        # 인식된 얼굴에 네모를 그린다.
        frame = cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 4)
        # 인식된 얼굴 데이터를 추출한다.
        faceROI = frame_gray[y:y+h, x:x+w]
        # 인식된 얼굴에서 눈을 인식한다.
        eyes = eyes_cascade.detectMultiScale(faceROI)
        # print(eyes)
        # 인식된 눈의 수 만큼 반복한다.
        for x2, y2, w2, h2 in eyes :
            # 원의 중심점
            eye_center = x + x2 + w2 // 2, y + y2 + h2 // 2
            # 반경
            radius = int(round((w2 + h2) * 0.25))
            # 원을 그린다.
            frame = cv2.circle(frame, eye_center, radius, (255, 0, 0), 4)
        
    # 그린다.
    cv2.imshow('face detection', frame)
    
    # 키를 누르면 중단한다.
    if cv2.waitKey(1) & 0xFF == ord('q') :
        break

[[ 484   88  240  240]
 [ 849  198  207  207]
 [ 253  339  192  192]
 [1381  716   71   71]]
[[847 198 217 217]
 [489  92 231 231]
 [248 338 208 208]]
[[843 195 229 229]
 [250 347 206 206]
 [491  96 229 229]]
[[ 847  200  223  223]
 [ 256  353  205  205]
 [ 489   96  240  240]
 [1455  766   79   79]]
[[ 256  353  205  205]
 [ 847  200  223  223]
 [ 490   97  238  238]
 [1455  766   79   79]]
[[854 208 215 215]
 [497 105 230 230]
 [260 361 205 205]]
[[857 212 208 208]
 [498 108 229 229]
 [266 372 203 203]]
[[ 502  113  228  228]
 [ 855  213  220  220]
 [ 263  380  214  214]
 [ 452  818   63   63]
 [1463  776   78   78]]
[[855 213 224 224]
 [503 116 231 231]]
[[855 216 227 227]
 [503 119 236 236]]
[[856 219 224 224]
 [505 119 234 234]]
[[862 224 217 217]
 [510 123 228 228]
 [460 846  64  64]]
[[510 125 233 233]
 [864 220 224 224]
 [461 853  64  64]]
[[516 128 227 227]
 [867 224 221 221]
 [460 856  67  67]]
[[459 858  70  70]
 [869 227 217 217]
 [513 126 233 233]]
[[ 458  863   69   69]
 

In [7]:
cv2.destroyAllWindows()